services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--auth", "--bind_ip", "0.0.0.0"]

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: "mongodb://admin:pass@mongodb:27017/"
    ports:
      - "8081:8081"
    networks:
      - mongo-network

  demo-apib-service:
    container_name: demo-apib-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5673:5673"
    restart: always
    networks:
      - mongo-network
    depends_on:
      - mongodb

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
